version: '3'

services:
  mongo:
    container_name: nanomixer-mongo
    hostname: mongo
    image: mongo
    restart: always
    volumes:
      - ./server/storage/db:/data/db
    ports:
      - "27017:27017"
  redis:
    container_name: nanomixer-redis
    hostname: redis
    image: redis
    restart: always
  app:
    container_name: nanomixer-app
    depends_on:
      - mongo
      - redis
    build: .docker/app
    ports:
      - "80:3000"
    restart: always
    volumes:
      - .:/app
  tor:
    container_name: nanomixer-tor
    depends_on:
      - app
    build: .docker/tor
    restart: always
    volumes:
      - ./server/storage/tor:/var/lib/tor
  nano:
    container_name: nanomixer-nano
    image: nanocurrency/nano
    restart: always
    volumes:
      - ./server/storage/nano:/root/Nano
